### ISSUE TITLE
Ошибка: Each key of IDictionary must be alphanumeric and start with character.

### ISSUE THREAD

**Issue by sheigor** [zhichkin/dajet-studio#1]
Все поля в скрипте обязательно должны иметь псевдонимы иначе возникает ошибка. Почему нельзя использовать уже известные имена полей?

**Comment by zhichkin** [comment]
Да, всё верно. В текущей реализации все поля должны иметь псевдоним.
Планируется исправить в последующих релизах.
Номер релиза пока сообщить не смогу.
